import heapq

"""
TASK 2: Algorithm Understanding using AI

Implementations generated by AI tools:
1. Binary Search
2. Merge Sort
3. Dijkstra's Algorithm
"""

# 1. Binary Search
def binary_search(arr, target):
    """
    Search for a target value within a sorted array.
    Time Complexity: O(log n)
    Space Complexity: O(1)
    """
    left, right = 0, len(arr) - 1
    
    while left <= right:
        mid = left + (right - left) // 2
        
        if arr[mid] == target:
            return mid
        elif arr[mid] < target:
            left = mid + 1
        else:
            right = mid - 1
            
    return -1

# 2. Merge Sort
def merge_sort(arr):
    """
    Sort an array using the divide-and-conquer strategy.
    Time Complexity: O(n log n)
    Space Complexity: O(n)
    """
    if len(arr) > 1:
        mid = len(arr) // 2
        left_half = arr[:mid]
        right_half = arr[mid:]

        merge_sort(left_half)
        merge_sort(right_half)

        i = j = k = 0

        # Merge the two halves
        while i < len(left_half) and j < len(right_half):
            if left_half[i] < right_half[j]:
                arr[k] = left_half[i]
                i += 1
            else:
                arr[k] = right_half[j]
                j += 1
            k += 1

        # Check if any element was left
        while i < len(left_half):
            arr[k] = left_half[i]
            i += 1
            k += 1

        while j < len(right_half):
            arr[k] = right_half[j]
            j += 1
            k += 1

# 3. Dijkstra's Algorithm
def dijkstra(graph, start):
    """
    Find the shortest paths from a starting node to all other nodes.
    Time Complexity: O((V + E) log V) using a priority queue.
    Space Complexity: O(V)
    
    Graph representation: dictionary where keys are nodes and values are lists of (neighbor, weight) tuples.
    """
    distances = {node: float('infinity') for node in graph}
    distances[start] = 0
    priority_queue = [(0, start)]
    visited = set()

    while priority_queue:
        current_distance, current_node = heapq.heappop(priority_queue)

        if current_node in visited:
            continue
            
        visited.add(current_node)

        # Optimization: We already have a shorter path
        if current_distance > distances[current_node]:
            continue

        for neighbor, weight in graph[current_node]:
            distance = current_distance + weight

            if distance < distances[neighbor]:
                distances[neighbor] = distance
                heapq.heappush(priority_queue, (distance, neighbor))

    return distances

# Test cases
if __name__ == "__main__":
    print("--- Binary Search Test ---")
    arr = [2, 3, 4, 10, 40]
    target = 10
    print(f"Array: {arr}, Target: {target}")
    print(f"Index found: {binary_search(arr, target)}")
    
    print("\n--- Merge Sort Test ---")
    arr_unsorted = [12, 11, 13, 5, 6, 7]
    print(f"Unsorted array: {arr_unsorted}")
    merge_sort(arr_unsorted)
    print(f"Sorted array: {arr_unsorted}")
    
    print("\n--- Dijkstra's Algorithm Test ---")
    graph = {
        'A': [('B', 1), ('C', 4)],
        'B': [('A', 1), ('C', 2), ('D', 5)],
        'C': [('A', 4), ('B', 2), ('D', 1)],
        'D': [('B', 5), ('C', 1)]
    }
    start_node = 'A'
    print(f"Graph: {graph}")
    print(f"Shortest paths from {start_node}: {dijkstra(graph, start_node)}")
